//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICalcService")]
public interface ICalcService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/GetShortestPath", ReplyAction="http://tempuri.org/ICalcService/GetShortestPathResponse")]
    string[][] GetShortestPath(string from, string to);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/GetShortestPath", ReplyAction="http://tempuri.org/ICalcService/GetShortestPathResponse")]
    System.Threading.Tasks.Task<string[][]> GetShortestPathAsync(string from, string to);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICalcServiceChannel : ICalcService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CalcServiceClient : System.ServiceModel.ClientBase<ICalcService>, ICalcService
{
    
    public CalcServiceClient()
    {
    }
    
    public CalcServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CalcServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CalcServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CalcServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string[][] GetShortestPath(string from, string to)
    {
        return base.Channel.GetShortestPath(from, to);
    }
    
    public System.Threading.Tasks.Task<string[][]> GetShortestPathAsync(string from, string to)
    {
        return base.Channel.GetShortestPathAsync(from, to);
    }
}
