//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IDataManService")]
public interface IDataManService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataManService/SaveNode", ReplyAction="http://tempuri.org/IDataManService/SaveNodeResponse")]
    void SaveNode(string node);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataManService/SaveNode", ReplyAction="http://tempuri.org/IDataManService/SaveNodeResponse")]
    System.Threading.Tasks.Task SaveNodeAsync(string node);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IDataManServiceChannel : IDataManService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DataManServiceClient : System.ServiceModel.ClientBase<IDataManService>, IDataManService
{
    
    public DataManServiceClient()
    {
    }
    
    public DataManServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DataManServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DataManServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DataManServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void SaveNode(string node)
    {
        base.Channel.SaveNode(node);
    }
    
    public System.Threading.Tasks.Task SaveNodeAsync(string node)
    {
        return base.Channel.SaveNodeAsync(node);
    }
}
